0:
  -
    x: 0
    y: -0.05
  -
    x: -0.1
    y: 0
  -
    x: 0
    y: 0.05
  -
    x: 0.1
    y: 0
1:
  -
    x: -0.1
    y: 0
2:
  -
    x: 0
    y: -0.05
  -
    x: -0.05
    y: 0
  -
    x: 0
    y: 0.05
  -
    x: -0.05
    y: 0
  -
    x: 0
    y: -0.05
3:
  -
    x: 0
    y: -0.05
  -
    x: -0.05
    y: 0
  -
    x: 0
    y: 0.05
  -
    x: 0
    y: -0.05
  -
    x: -0.05
    y: 0
  -
    x: 0
    y: 0.05
4:
  -
    x: -0.05
    y: 0
  -
    x: 0
    y: -0.1
  -
    x: 0
    y: 0.05
  -
    x: 0.05
    y: 0
  -
    x: -0.1
    y: 0
5:
  -
    x: 0
    y: -0.05
  -
    x: 0
    y: 0.05
  -
    x: -0.05
    y: 0
  -
    x: 0
    y: -0.05
  -
    x: -0.05
    y: 0
  -
    x: 0
    y: 0.05
6:
  -
    x: 0
    y: -0.05
  -
    x: 0
    y: 0.05
  -
    x: -0.1
    y: 0
  -
    x: 0
    y: -0.05
  -
    x: 0.05
    y: 0
  -
    x: 0
    y: 0.05
7:
  -
    x: 0
    y: -0.05
  -
    x: -0.1
    y: 0
8:
  -
    x: -0.1
    y: 0
  -
    x: 0
    y: -0.05
  -
    x: 0.05
    y: 0
  -
    x: 0
    y: 0.05
  -
    x: 0
    y: -0.05
  -
    x: 0.05
    y: 0
  -
    x: 0
    y: 0.05
9:
  -
    x: 0
    y: -0.05
  -
    x: -0.1
    y: 0
  -
    x: 0.05
    y: 0
  -
    x: 0
    y: 0.05
  -
    x: 0.05
    y: 0
